### ISSUE TITLE
Syntax error during configure

### ISSUE THREAD

**Issue by smolarium** [Arkq/svar#4]
When I execute:

../configure --enable-sndfile --enable-mp3lame --enable-vorbis

I have this effect:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for library containing sqrt... -lm
checking for library containing pthread_create... -lpthread
../configure: line 3622: syntax error near unexpected token `ALSA,'
../configure: line 3622: `PKG_CHECK_MODULES(ALSA, alsa)'

**Comment by Arkq** [comment]
You've got the syntax error because apparently your host lacks `pkg-config` tool. Anyway, I'm closing this issue, because I've changed build system to CMake.
