### ISSUE TITLE
Full date in timestamp

### ISSUE THREAD

**Issue by formatc2k1** [Arkq/svar#8]
I just started using this great app, thank you for making it! Is it possible that the output file name (aka timestamp) includes at least the month, but preferably the full date?

Thanks,
Balazs

**Comment by Arkq** [comment]
Now it will be possible to specify custom file name (with directories, etc.) with strftime(3) format string, e.g.:
```
svar -o ogg /recordings/myname-%Y-%m-%d-%H-%M-%S
```

**Comment by formatc2k1** [comment]
It works great, thank you!
