### ISSUE TITLE
Last half second of OGG recording missing

### ISSUE THREAD

**Issue by jamesTSCoop** [arkq/svar#9]
Hey, svar is cool, just what I'm looking for atm.  I was hoping to save to ogg format but I notice that the last half second or so of recording (when I hit ctrl-C to stop recording) is missing.  This doesn't happen when I save to mp3 format, nor does it happen with I save to ogg with parecord.  I'm just curious if you know why this might be happening.  I'm a software programmer, so if you point me int the right direction I might be able to fix it if you don't have the time/interest.

**Comment by arkq** [comment]
>  I'm a software programmer, so if you point me int the right direction I might be able to fix it if you don't have the time/interest.

I guess that some "flush" functionality is missing here: https://github.com/arkq/svar/blob/master/src/writer_vorbis.c#L105 Read documentation for vorbis to see how to properly end file write. If you will be able to fix that, I'd be glad if you could provide a PR with the fix.

**Comment by jamesTSCoop** [comment]
Yup, OGG container won't create "inefficient" pages via ogg_stream_pageout() if there aren't enough vorbis packets to make an "efficient" OGG page, so an ogg_stream_flush() is needed to flush any remaining vorbis packets before the container is closed.  PR coming shortly.
